export const idea = {
    id:"ID", 
    discipline:"Discipline", 
    name:"Name", 
    scope:"Scope", 
    category:"Category", 
    _type:"Type", 
    process_nodes:"Process", 
    summary:"High-Level Description", 
    motivation:"Motivation", 
    priority:"Priority", 
    status:"Status", 
    status_comment:"Status Comment", 
    resources:"Resource Estimate", 
    link_page:"IP link", 
    owner:"Owner", 
    dm_sponsor:"DM Sponsor", 
    start_date:"Start Date", 
    requirement_review:"Requirement Review", 
    complete_date:"Complete Date", 
    proposer:"Proposer", 
    date_added:"Date Added", 
    external_link:"External Link(s)", 
    description:"Additional Notes", 
    reviewers:"Reviewers", 
    "projects":"Projects", 
    "diagrams":"Diagrams", 
    "attachments":"Attachments", 
};
export const max_len = {
    id:"None", 
    discipline:"None", 
    name:"30", 
    scope:"None", 
    category:"None", 
    _type:"10", 
    process_nodes:"None", 
    summary:"200", 
    motivation:"30", 
    priority:"None", 
    status:"None", 
    status_comment:"30", 
    resources:"100", 
    link_page:"150", 
    owner:"None", 
    dm_sponsor:"None", 
    start_date:"None", 
    requirement_review:"None", 
    complete_date:"None", 
    proposer:"None", 
    date_added:"None", 
    external_link:"None", 
    description:"None", 
    reviewers:"None", 
};

