#!/bin/sh
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi
PASS=true
echo "\n校验 Javascript:\n"
# Check for eslint
which eslint &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "\t\033[41m请安装： ESlint\033[0m"
  exit 1
fi
for FILE in $STAGED_FILES
do
  eslint "$FILE"
  if [[ "$?" == 0 ]]; then
    echo "\t\033[32mESLint 通过: $FILE\033[0m"
  else
    echo "\t\033[41mESLint 失败: $FILE\033[0m"
    PASS=false
  fi
done
echo "\nJavascript 校验完成!\n"
if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m 您提交的文件中有代码未通过eslint监测，请修复后提交！\n"
  exit 1
else
  echo "\033[42m提交成功！\033[0m\n"
fi
exit $?